### ISSUE TITLE
Discordに課せられたAPI BANの解除

### ISSUE THREAD

**Issue by merunno** [BattleField6-JapanCommunity/Battlefield-2042#2]
![image](https://user-images.githubusercontent.com/82575685/121684226-60861700-caf9-11eb-80da-99b1457c59fd.png)

```
DiscordAPIError: Your bot has been flagged by our anti-spam system for abusive behavior. Please reach out to our team by going to https://dis.gd/report and appeal this action taken on your bot.
    at RequestHandler.execute (C:\Users\piki0\Documents\disbot_discord.js\battlefield-2042\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\piki0\Documents\disbot_discord.js\battlefield-2042\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async User.createDM (C:\Users\piki0\Documents\disbot_discord.js\battlefield-2042\node_modules\discord.js\src\structures\User.js:252:18) {
  method: 'post',
  path: '/users/852225229106184213/channels',
  code: 20026,
  httpStatus: 403
}
```

**Comment by merunno** [comment]
BOT APPを削除したので解除できました
